version: '3.8'
services:
  web:
    container_name: api_container
    build:
      context: .
      dockerfile: api.Dockerfile
    network_mode: "host"
    # Link to containers in another service
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql
    container_name: db_container
    environment:
      MYSQL_ROOT_PASSWORD: MyApplication92
      MYSQL_DATABASE:      dbtest
    network_mode: "host"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10




  